### ISSUE TITLE
white in svg turns to black in png

### ISSUE THREAD

**Issue by auval** [sterlp/svg2png#1]
Thanks for this awesome project!
One critical issue that I've found is that white in svg turns to black in png.
I've used this command (on the unzipped attached svg):
`svg2png -android-launch -n icon_n.png -f test.svg`
I've tried changing the white color to off-white, and it didn't fix the problem.

![ic_launcher](https://cloud.githubusercontent.com/assets/10644518/21588123/403ed9fc-d0ec-11e6-9bac-8a418cb825e2.png)

[test.svg.zip](https://github.com/sterlp/svg2png/files/680671/test.svg.zip)

**Comment by auval** [comment]
found the problem: it was complex style inside the svg tag. batik library mishandled this.
I fix it by modifying the svg.

**Comment by sterlp** [comment]
Great, as I just dug a bit into the library code and couldn't find anything obvious which is wrong. I have seen some black in the SVG, but by just removing it, I couldn't easy fix it too.

Thanks for the feedback.
