### ISSUE TITLE
Option to only export RGB instead of RGBA

### ISSUE THREAD

**Issue by pseandersson** [sterlp/svg2png#11]
Hi,

What a nice little tool this is :)

I received an issue with app store connect that my icon had a transparency channel despite I've got an opaque background.

Would it be possible to add an option to output it in RGB instead of RGBA?

**Comment by sterlp** [comment]
Hi,

I assume this would be this key right?
https://xmlgraphics.apache.org/batik/javadoc/org/apache/batik/transcoder/image/ImageTranscoder.html#KEY_FORCE_TRANSPARENT_WHITE

Cheers

Paul

**Comment by sterlp** [comment]
Could you please try https://github.com/sterlp/svg2png/releases/tag/v1.0.0
