### ISSUE TITLE
Update mvn central

### ISSUE THREAD

**Issue by culmat** [sterlp/svg2png#20]
Hi Paul,

At https://central.sonatype.com/artifact/org.sterl.svg2png/svg2png a two year old 0.2.4 is published.
Can you please publish an current version?
You can also automate this via maven / github actions, see https://github.com/baloise/ossrh-pipeline-demo and a real life example: 
https://github.com/baloise/orchestra-maven-plugin/blob/master/development.md

Thanks & best regards,
Matthias

**Comment by sterlp** [comment]
Added the release pipeline
