### ISSUE TITLE
No resize from json configuration file

### ISSUE THREAD

**Issue by akelix** [sterlp/svg2png#21]
Tryes to prepare macos iconset from svg

`
{
  "files": [
    {
      "directory": "icon.iconset",
      "nameSuffix": "_16x16",
      "height": 16,
      "width": 16
    },{
      "directory": "icon.iconset",
      "nameSuffix": "_16x16@2x",
      "height": 32,
      "width": 32
    },{
      "directory": "icon.iconset",
      "nameSuffix": "_32x32",
      "height": 32,
      "width": 32
    },{
      "directory": "icon.iconset",
      "nameSuffix": "_32x32@2x",
      "height": 64,
      "width": 64
    },{
      "directory": "icon.iconset",
      "nameSuffix": "_128x128",
      "height": 128,
      "width": 128
    },{
      "directory": "icon.iconset",
      "nameSuffix": "_128x128@2x",
      "height": 256,
      "width": 256
    },{
      "directory": "icon.iconset",
      "nameSuffix": "_256x256",
      "height": 256,
      "width": 256
    },{
      "directory": "icon.iconset",
      "nameSuffix": "_256x256@2x",
      "height": 512,
      "width": 512
    },{
      "directory": "icon.iconset",
      "nameSuffix": "_512x512",
      "height": 512,
      "width": 512
    },{
      "directory": "icon.iconset",
      "nameSuffix": "_512x512@2x",
      "height": 1024,
      "width": 1024
    }
  ]
}
`

All Images in result directory has the same resolution. 256x256. Like svg has.
`
<svg
   width="240.0px"
   height="240.0px"
`

I think the problem is [here](https://github.com/sterlp/svg2png/blob/716a5923b1ebf366b1715651395e79b7816a5c27/src/main/java/org/sterl/svg2png/CliOptions.java#L85)
Width and height are always overridden from absent command line argument

Simple solution could be applied [here](https://github.com/sterlp/svg2png/blob/716a5923b1ebf366b1715651395e79b7816a5c27/src/main/java/org/sterl/svg2png/config/OutputConfig.java#L47)

`  
  public void applyOutputSize(int width, int height) {
        for (FileOutput fileOutput : files) {
            if(width > 0){
                fileOutput.setWidth(width);
            }
            if(height > 0){
                fileOutput.setHeight(height);
            }
        }
    }
`

**Comment by sterlp** [comment]
thanks yes this seems to be the issue, I need to build a test for this ...

**Comment by sterlp** [comment]
https://github.com/sterlp/svg2png/pull/22
