### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by c0dehunter** [sterlp/svg2png#3]
I have latest JDK in my path, but when trying to run 

`java svg2png`

I get

> Error: Could not find or load main class svg2png

Is it me or is there a problem with the implementation?

**Comment by c0dehunter** [comment]
Ah, I should run it as 

`java -jar svg2png`

Maybe this could be posted in instructions.

**Comment by sterlp** [comment]
I will update the readme file, thanks.
